server:
  port: 8080
spring:
  application:
    name: "authentication-microservice"
  devtools:
    add-properties: false
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8090"

adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "pragma_autenticacion"
    schema: "public"
    username: "postgres"
    password: "postgres"

routes:
  paths:
    users: "/api/v1/usuarios"
    userByDocument: "/api/v1/usuarios/{docNumber}"
